"""Update models to use UUID and add new tables

Revision ID: 0b4205b67d07
Revises: 
Create Date: 2025-03-29 21:50:23.704528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0b4205b67d07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('captures', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('captures', 'site_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index('ix_captures_id', table_name='captures')
    op.drop_column('captures', 'tags')
    op.alter_column('menu_structures', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('menu_structures', 'site_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('menu_structures', 'capture_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('page_screenshots', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('page_screenshots', 'page_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('page_tags', 'page_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('page_tags', 'tag_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('pages', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('pages', 'site_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('pages', 'capture_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.add_column('screenshots', sa.Column('screenshot_path', sa.String(), nullable=True))
    op.add_column('screenshots', sa.Column('thumbnail_path', sa.String(), nullable=True))
    op.alter_column('screenshots', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('screenshots', 'capture_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index('ix_screenshots_id', table_name='screenshots')
    op.alter_column('site_tags', 'site_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('site_tags', 'tag_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('sites', sa.Column('first_captured_at', sa.DateTime(), nullable=True))
    op.add_column('sites', sa.Column('last_captured_at', sa.DateTime(), nullable=True))
    op.add_column('sites', sa.Column('capture_count', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('status', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('sites', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_sites_id', table_name='sites')
    op.drop_column('sites', 'tags')
    op.alter_column('tags', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('sites', sa.Column('tags', sqlite.JSON(), nullable=True))
    op.create_index('ix_sites_id', 'sites', ['id'], unique=False)
    op.alter_column('sites', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('sites', 'notes')
    op.drop_column('sites', 'status')
    op.drop_column('sites', 'capture_count')
    op.drop_column('sites', 'last_captured_at')
    op.drop_column('sites', 'first_captured_at')
    op.alter_column('site_tags', 'tag_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('site_tags', 'site_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_index('ix_screenshots_id', 'screenshots', ['id'], unique=False)
    op.alter_column('screenshots', 'capture_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('screenshots', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('screenshots', 'thumbnail_path')
    op.drop_column('screenshots', 'screenshot_path')
    op.alter_column('pages', 'capture_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('pages', 'site_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('pages', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('page_tags', 'tag_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('page_tags', 'page_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('page_screenshots', 'page_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('page_screenshots', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('menu_structures', 'capture_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('menu_structures', 'site_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('menu_structures', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('captures', sa.Column('tags', sqlite.JSON(), nullable=True))
    op.create_index('ix_captures_id', 'captures', ['id'], unique=False)
    op.alter_column('captures', 'site_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('captures', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
